### ISSUE TITLE
bug: หน้า `/senate/votelog` มี label "ไม่ลงมติ" ซ้ำซ้อน และค่า NaN

### ISSUE THREAD

**Issue by rootEnginear** [wevisdemo/they-work-for-us#15]
หน้า `/senate/votelog` มี label "ไม่ลงมติ" ซ้ำซ้อน
![image](https://user-images.githubusercontent.com/7108662/193582511-1d85bc5a-88d4-46ec-92cb-15ed9a8abc06.png)

**Comment by Th1nkK1D** [comment]
ล่าสุดมี `NaN` ด้วย ; - ; น่าจะต้องไล่ดูข้อมูลว่ามีอะไรที่ไม่ใช่ตัวเลขปนเข้ามา

![image](https://user-images.githubusercontent.com/8860448/215734682-0c309245-48cc-4d05-ae35-03d43d9b0ceb.png)

## Dev starting point

หน้านี้อยู่ที่ไฟล์ `src/pages/senate/votelog.js`

**Comment by Th1nkK1D** [comment]
Merged #33
