### ISSUE TITLE
feat(/party/ชื่อพรรค): เพิ่มตำแหน่ง รองหัวหน้าพรรค ในหน้าแต่ละพรรคการเมือง

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#17]
![image](https://user-images.githubusercontent.com/54769527/198540273-b713d8f0-b056-4c5b-997b-cbfe1e56cd03.png)

**Comment by thanisara-r** [comment]
@namsaisup ช่วยอัพเดท Design ให้ด้วยค่ะ

Maximum 5 คน

**Comment by namsaisup** [comment]
ดูดไซน์ใน [figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=831%3A10326&t=tx5cPh0I6Qp3DhFu-1) หน้า 👥Profile กลุ่ม_feb2023
<img width="673" alt="CleanShot 2566-01-30 at 19 41 41@2x" src="https://user-images.githubusercontent.com/123941533/215479987-8ea03ed1-e6fa-4e65-999d-cca39e0001cb.png">

**Comment by thanisara-r** [comment]
@Th1nkK1D อยู่ในชีท [T] Party คอลัมน์ party_deputy ค่า

https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=1527118532&range=R:R
