### ISSUE TITLE
feat(/representatives): เพิ่มตำแหน่ง วิปรัฐบาล ในหน้ารวม ส.ส.

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#19]
![image](https://user-images.githubusercontent.com/54769527/198542180-dcdf49ff-d1bb-4e09-8927-d1e1a34d97e6.png)

**Comment by rootEnginear** [comment]
ข้อมูลตำแหน่งวิปรัฐบาลมีอยู่ใน Sheet แล้วหรือยังไม่มีนะคะ

**Comment by thanisara-r** [comment]
@namsaisup ช่วยอัพเดท Design ให้ด้วยค่ะ

**Comment by namsaisup** [comment]
ดูดีไซน์ใน [figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=831%3A10326&t=tx5cPh0I6Qp3DhFu-1) หน้า 👥Profile กลุ่ม_feb2023
<img width="557" alt="CleanShot 2566-01-30 at 19 40 23" src="https://user-images.githubusercontent.com/123941533/215479659-f416686b-1e7e-4f36-bdac-7fdb6d8af91c.png">

**Comment by Th1nkK1D** [comment]
@thanisara-r ผมหาไม่เจอแฮะว่ามันดึงจาก column ไหนใน sheet นะครับ

**Comment by thanisara-r** [comment]
@Th1nkK1D อยู่ในชีท [T] Party คอลัมน์ whip ค่า

https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=1527118532&range=O:O

**Comment by Th1nkK1D** [comment]
## Dev Starting point

Data is now available as described in #51 

Add a property in the GraphQL query and update UI
