### ISSUE TITLE
feat(/votelog/:id): ปรับ Waffle Map เพิ่มคนไม่เข้าร่วมลงมติและจัดกลุ่มย่อยตามพรรค

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/they-work-for-us#2]
![image](https://user-images.githubusercontent.com/8860448/190659564-e6096236-6046-4acb-9d9a-191cb4bec0f0.png)

- เพิ่มประเภท "คนไม่เข้าประชุม"
- จัด Waffle ให้มีกลุ่มตามพรรค
- ในแต่ละพรรค Waffle จะมีกลุ่มย่อยเป็น 25 cells และมีได้มากสุด 2 column ในแต่ละ row

**Comment by Pimpatipan** [comment]
**ทำแล้ว**
เพิ่มประเภท "คนไม่เข้าประชุม"
ในแต่ละพรรค Waffle จะมีกลุ่มย่อยเป็น 25 cells และมีได้มากสุด 2 column ในแต่ละ row

**ยังไม่ทำ**
จัด Waffle ให้มีกลุ่มตามพรรค

สู้ๆ จ้า เย้

**Comment by rootEnginear** [comment]
![image](https://user-images.githubusercontent.com/7108662/192562030-cc4f5e09-be89-48dd-8595-1bb17ae51203.png)

Waffle หน้าแรก เอาเป็นเหมือนเดิมไหมคะ
