### ISSUE TITLE
feat(/party/ชื่อพรรค): เพิ่มให้ดู ผลการลงมติทั้งหมด ของพรรคนั้น ในหน้ารวมพรรค ได้

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#21]
ตอนนี้หน้าแต่ละพรรค ดูได้แค่ 6 การลงมติล่าสุด แต่อยากให้ดูผลการลงมติได้ทั้งหมด (เฉพาะผลโหวตของพรรคนั้นๆ) เหมือนหน้า https://theyworkforus.wevis.info/votelog <img width="994" alt="image" src="https://user-images.githubusercontent.com/54769527/213074307-d1431a62-12e8-4ca4-baab-2abb65c1c1f1.png">

**Comment by Th1nkK1D** [comment]
หน้านี้อยู่ที่ไฟล์ `src/templates/party-template.js` ครับ แนะนำให้เริ่มต้นจากจุดนี้

**Comment by bothonachiz** [comment]
ขอรับ issue นี้ไว้ทำครับ

**Comment by Th1nkK1D** [comment]
ปรึกษา @thanisara-r @namsaisup ครับ ผมลองเล่นจากที่ @bothonachiz ทำไว้ มันมี votelog เยอะมากๆ ผมเบลอเองที่เข้าใจว่า votelog จะอยู่ล่างสุดของหน้า ต่อให้ยาวก็ไม่กังวลมาก แต่จริงๆ มันมีสมาชิกในพรรคมาต่อ การที่ votelog ยาวขนาดนี้อาจจะทำให้คนไปไม่ถึงส่วนสมาชิกพรรคด้านล่างหรือเปล่านะ ซึ่งเอาจริงสมาชิกพรรคก็ยาวเหยียดพอกัน

ผมพอนึก solution ออกเร็วๆ ได้สองอัน
1. เพิ่ม table of content เหมือนเป็นลิ้งให้กดเลื่อนไป section ต่างๆ ได้ แล้วมีลิ้งย้อนขึ้นมาข้างบน (อันนี้ในมุม dev ง่ายดี)
2. ทำเป็น pagination อันนี้ซับซ้อนขึ้นมาหน่อย ในมุม dev ก็คงเป็น client-site pagination แหละไม่ต้องแยกหน้าจริงๆ

ปล. ถ้าประเมินว่ามีงานต้องทำประมาณนึงเดี๋ยวอาจจะเปิดเป็นอีก issue ครับ

https://user-images.githubusercontent.com/8860448/216985470-b0207f94-13f2-4e52-8d57-07ada6b1240c.mp4

**Comment by namsaisup** [comment]
@Th1nkK1D แบบนี้โอปะ (ดูใน[figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=831%3A10326&t=TZD3n50ft44NsOZa-1)หน้า👥หน้า Profile กลุ่ม_feb2023)
<img width="741" alt="CleanShot 2566-02-14 at 20 09 51@2x" src="https://user-images.githubusercontent.com/123941533/218748320-4bb19c4b-ee4b-405c-9f17-883d2b584659.png">

คือให้มีแถบ sticky สารบัญ โดยเมื่ออยู่ในsectionนั้นๆ ลูกศรชี้ลงจะหายไป และเมื่ออยู่ในsectionสมาชิก ลูกศรของแถบลงมติจะเปลี่ยนเป็นชี้ขึ้นแทน
<img width="746" alt="CleanShot 2566-02-14 at 20 07 13@2x" src="https://user-images.githubusercontent.com/123941533/218748319-29af0701-b3ed-48d7-9a7b-dea87575d39d.png">

**Comment by Th1nkK1D** [comment]
@namsaisup ชอบบบ ผมว่าเป็น solution ที่โอเคนะครับ เดี๋ยวผมเอาไปเปิด issue ใหม่

**Comment by Th1nkK1D** [comment]
Merged #35
