### ISSUE TITLE
feat(/people/ชื่อคน): เพิ่มการแบ่งส่วนการแสดงผลการโหวต เมื่ออยู่ต่างพรรค สำหรับ ส.ส. ที่ย้ายพรรค

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#27]
ตอนนี้ หน้า ส.ส. จะแสดงผลเป็นพรรคล่าสุด ไม่มีประวัติว่าเคยอยู่พรรคไหนมา ทำให้ผลโหวตเป็นของพรรคนั้นๆ พรรคเดียว
อยากให้แสดงผลโหวต แยกของพรรคเดิม และพรรคใหม่ด้วย

<img width="765" alt="image" src="https://user-images.githubusercontent.com/54769527/213076990-cdb85c02-9ea0-4611-9fcf-18a95e94626e.png">

**Comment by thanisara-r** [comment]
@namsaisup ช่วยอัพเดท Design ให้ด้วยค่ะ

**Comment by namsaisup** [comment]
อัพเดทดีไซน์แล้วค่ะ อยู่ใน [Figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=821%3A5221&t=tx5cPh0I6Qp3DhFu-1) หน้า 👤Profileสส_feb2023

โดยประกอบไปด้วย
1. เพิ่มประวัติการย้ายพรรคในการ์ดหน้าแรก (จะกระทบกับวิธีsetขนาดการ์ดProfileด้วย (เขียนบอกดีเทลไว้ในfigma))
<img width="383" alt="CleanShot 2566-01-30 at 18 46 08@2x" src="https://user-images.githubusercontent.com/123941533/215468747-c0527811-d48e-4445-88d4-6feeeab9edb1.png">
2. เพิ่ม dropdown สำหรับฟิลเตอร์ดูแยกตามพรรค
<img width="762" alt="CleanShot 2566-01-30 at 18 46 17@2x" src="https://user-images.githubusercontent.com/123941533/215468756-0d7d2504-d614-4c06-8e50-5eeadd255f8c.png">

**Comment by thanisara-r** [comment]
@Th1nkK1D ข้อมูลอยู่ในชีทนี้ แต่กำลังอยู่ระหว่างอัพเดทค่ะ (ใส่ตัวอย่างไว้บางส่วน)
https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=707580902

เมื่อย้ายพรรค จะมีแถวที่มีชื่อซ้ำ แต่ `party` และ `established_date` เปลี่ยนค่ะ

**Comment by Th1nkK1D** [comment]
## Dev Starting point

Data is now available as described in #51 

Add a property in the GraphQL query and update UI

**Comment by Th1nkK1D** [comment]
Implemented in dc60c41
