### ISSUE TITLE
admin: เพิ่มฐานข้อมูล ส.ส. ย้ายพรรค และทำให้ผลโหวตแสดงแยกกัน

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#28]
ตอนนี้ พรรคของ ส.ส. จะแสดงผลเป็นพรรคล่าสุด และไม่มีประวัติว่าเคยอยู่พรรคไหนมา ทำให้ผลโหวตเป็นของพรรคนั้นๆ พรรคเดียว
และหน้ารวมผลโหวตของแต่ละพรรค ก็จะได้ข้อมูลของ ส.ส. คนนั้นตอนโหวตพรรคอื่นมาด้วย
เช่น ศรีนวล เคยอยู่ก้าวไกล มาก่อนย้ายมา ภูมิใจไทย แต่ผลโหวตของศรีนวล จะรวมเป็นของภูมิใจไทย ทั้งในหน้าของ ศรีนวล และในหน้าของภูมิใจไทย

<img width="765" alt="image" src="https://user-images.githubusercontent.com/54769527/213076990-cdb85c02-9ea0-4611-9fcf-18a95e94626e.png">

ปรึกษา @Th1nkK1D @mixth ถ้าทำ database ส.ส. ย้ายพรรคเพิ่ม ระบุวันที่ย้ายพรรค และแมตช์กับวันที่ของการลงมติ เพื่อแยกได้ว่าผลโหวตอันไหนเป็นของพรรคใหม่และพรรคเดิม จะโอเคไหม

**Comment by mixth** [comment]
ในมุมการกรอกข้อมูล คิดว่าอย่างที่บอกคงเหมาะสมครับ

**Comment by wasdee** [comment]
อยากลองทำ PR นี้ ในส่วนการเตรียมข้อมูลครับ ตอนนี้ไปถึงไหนแล้วครับ

**Comment by wasdee** [comment]
ลองดูแหล่งข้อมูลการย้ายพรรคที่น่าจะใช้ได้ 
# Official Source
1. [สส official site](https://hris.parliament.go.th/ss_detail.php?sapa_id=82&ssp_id=21427&lang=th) + [wayback machine](https://web.archive.org/web/20211023152449/https://hris.parliament.go.th/ss_detail.php?sapa_id=82&ssp_id=21427&lang=th) - ไม่ได้เพราะพอย้ายพรรค `ssp_id` น่าจะเปลี่ยน
2. PDF search? Google Dork? บันทึกการประชุม? บันทึกการประชุมพรรค?
3. [สส official list](https://hris.parliament.go.th/ss_th.php) + [wayback machine](https://[web.archive.org](https://web.archive.org/web/20191001000000/https://hris.parliament.go.th/ss_th.php)/web/20191001000000/https://hris.parliament.go.th/ss_th.php) +  [สส official site](https://hris.parliament.go.th/ss_detail.php?sapa_id=82&ssp_id=21427&lang=th) - wayback machine is unreliable. the date likely to diff by +-30days. 
4. [สส official site](https://hris.parliament.go.th/ss_detail.php?sapa_id=82&ssp_id=21427&lang=th) - no history + dev tools showed data returned as html, not json.
# Secondary
1. [Wikipedia](https://th.wikipedia.org/wiki/%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B8%99%E0%B8%A7%E0%B8%A5_%E0%B8%9A%E0%B8%B8%E0%B8%8D%E0%B8%A5%E0%B8%B7%E0%B8%AD) + chatGPT-like น่าจะได้
2.

**Comment by Th1nkK1D** [comment]
@wasdee ยินดีต้อนรับคร้าบ ผมเพิ่งเห็นว่า issue มัน duplicate กับ #27 ตอนนี้ข้อมูลเรามีเรียบร้อยแล้วครับ แต่ว่าเพราะมันต้องเพิ่มตารางใหม่ ผมเลยกำลังจัดการ structure ข้อมูลหลังบ้านอยู่ (ตอนนี้ถ้าดึงข้อมูลใหม่ลงมา build จะ fail ขอซ่่อมตรงนี้ก่อน) คาดว่าภายในต้นสัปดาห์หน้าจะพร้อมให้เอาไปทำ frontend ต่อได้ครับผม เดี๋ยวผมจะปิด issue นี้ ถ้าสนใจรับไปทำต่อไปเม้นไว้ใน #27 ได้เลยครับ

**Comment by wasdee** [comment]
ได้ครับ 😊 ถ้ามีงาน data อะไรแท็กมาได้ครับ frontend stack นี้พี่ไม่ค่อยถนัดเท่าไร ขอข้าม @Th1nkK1D

**Comment by Th1nkK1D** [comment]
> ได้ครับ blush ถ้ามีงาน data อะไรแท็กมาได้ครับ frontend stack นี้พี่ไม่ค่อยถนัดเท่าไร ขอข้าม @Th1nkK1D

รับทราบครับผม scope งานที่สนใจเป็นประมาณไหนบ้างครับ ถ้ามีอะไรที่ตรงผมจะได้มาชวน

**Comment by wasdee** [comment]
จริงๆก็ generalist 😂 มาก
แต่ยังไม่อยากเรียนรู้อะไรใหม่เพิ่มแบบหนักๆ ช่วงนี้งานที่บ. เยอะไปหมด 555

1. data crawler
2. ETL
3. EDA
4. ML
5. Python
6. comment on UX

Noob and want to learn
1. sveltekit - tailwind css
2. deeper devtools
3. golang
4. mapbox and https://[kepler.gl](https://kepler.gl/)/
