### ISSUE TITLE
feat(/votelog): เพิ่ม Search ชื่อมติ

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/they-work-for-us#3]
![image](https://user-images.githubusercontent.com/8860448/190660925-3941062a-daf9-4d32-b819-51a9b5b0a342.png)

- เมื่อพิมพ์จะ suggest ชื่อมติมาให้แบบ dropdown
- กดที่ชื่อ มติเพื่อลิ้งไปหน้ามตินั้นๆ เลย

![image](https://user-images.githubusercontent.com/8860448/192267340-3911b484-e686-4c71-a4ae-c6ab3c03620e.png)

- กรณีที่ไม่เจอผลลัพธ์

![image](https://user-images.githubusercontent.com/8860448/192267483-9baa163e-fed5-4783-a212-86b0843f98a6.png)

## Possible Solution
- Query votelog title และ legal_title มาเพิ่มเพื่อใช้ filter substring

**Comment by thanisara-r** [comment]
อยากให้เสิร์ชได้จากทั้งคอลัมน์ title และ legal_title จากใน sheet

**Comment by rootEnginear** [comment]
ในกรณีการค้นหาแล้วมีเว้นวรรค เช่น "ไม่ไว้วางใจ ธนาธร" นับเป็น exact match (`/ไม่ไว้วางใจ ธนาธร/g`) หรือ or (`/ไม่ไว้วางใจ|ธนาธร/g`)?

**Comment by thanisara-r** [comment]
ขอเป็น `or (/ไม่ไว้วางใจ|ธนาธร/g)` ค่ะ
