### ISSUE TITLE
admin: เพิ่มข้อมูลสมัยของ พรรค / ส.ส. / ส.ว. / ครม. ได้มากกว่า 1 สมัย ใน database

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#30]
ปรึกษา @mixth @Th1nkK1D 

- เรามีคอลัมน์ `party_ordinal` `established_date` `dissolved_date` ในชีท [T] Party เพื่อบอกสมัยของแต่ละสภา/ครม. อยู่แล้ว
- ถ้าเราเพิ่มคอลัมน์ `party_ordinal` ในชีท [T] People เพื่อให้รู้ว่าข้อมูลของคนนั้นอยู่ในสมัยไหน พอไหม
- ส่วน [T] Votelog มีวันที่อยู่แล้ว สามารถลิงก์กับ `established_date` `dissolved_date` ได้เลยไหม?
- และ [T] PeopleVote ลิงก์กับ [T] Votelog อยู่แล้ว น่าจะไม่มีปัญหาอะไร

หรือไม่แน่ใจว่า พอจะย้ายไป NocoDB แล้วจะแยกตารางยังไงไหม?

Note : [T] People สมัยหน้า คนเดิมก็จะเพิ่มแถวใหม่ เพราะอาจจะย้ายพรรค ย้ายเขตได้

**Comment by Th1nkK1D** [comment]
ถ้าไม่มีเหตุการที่คนนึงย้ายในสมัยเดียวกัน ผมว่าวิธีที่เสนอมาก็โอเคนะครับ เรื่องย้ายตารางไป noco ตอนนี้ผมคิดว่าจะไม่เปลี่ยนเยอะในตอนนี้ครับ
