### ISSUE TITLE
feat(/people/ชื่อคน): เพิ่มการ search ชื่อมติ ในหน้าบุคคล

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#31]
![image](https://user-images.githubusercontent.com/54769527/215438127-18dc4498-ebc2-4f0c-b262-3eb29a13eef3.png)

เช่น อยากดูมติเกี่ยวกับ 'รัฐธรรมนูญ' ของ ส.ส. A

**Comment by thanisara-r** [comment]
@namsaisup ช่วยเพิ่ม design ด้วยค่ะ

**Comment by namsaisup** [comment]
อัพเดทดีไซน์แล้วค่ะ อยู่ใน [figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=821%3A5221&t=tx5cPh0I6Qp3DhFu-1) หน้า👤_Profileสส_feb2023_
<img width="1391" alt="CleanShot 2566-01-30 at 18 43 34" src="https://user-images.githubusercontent.com/123941533/215467858-8bcfc0e0-5bcc-4c3e-9614-2c52b196cfa8.png">

**Comment by Th1nkK1D** [comment]
## Dev starting point

- เรามี VoteSearch component ที่ใช้ style เดียวกันอยู่ที่ `src/components/votesearch/VoteSearch.js` (ปัจจุบันใช้ในหน้า [/votelog](https://theyworkforus.wevis.info/votelog)) แนะนำให้ refactor ออกมาให้ reuse กับ issue นี้ได้
- หน้าบุคคลอยู่ที่ไฟล์ `src/components/peopleVote.js`

**Comment by Th1nkK1D** [comment]
@namsaisup มี feedback เรื่อง epty state message นิดนึงครับ
1. สีแดงอาจจะแรงไปไหมนะ55555 ผมรู้สึกว่ามันหาไม่เจอแต่ไม่ถึงกับเป็น error ไม่ค่อยเห็นคนใช้สีแดงกับการ search ไม่เจอ
2. มันจะเป็น message ที่เกิดจากการเลือก**ประเภทการลงคะแนน** + **keyword ในชื่อ** คู่กัน ผมคิดว่าใช้คำว่า **"ไม่มีมติชื่อนี้"** มันเหมือนจะถูกแค่ครึ่งเดียว น่าจะต้องปรับคำ

อันนี้คือ design ใน figma
![image](https://user-images.githubusercontent.com/8860448/216582747-d4904133-b4c2-424e-a457-3a07a4f00d8b.png)

ส่วนอันนี้คือ message ปัจจุบันที่เลือกได้แค่ประเภท
![image](https://user-images.githubusercontent.com/8860448/216582884-ace2f63b-d6ef-44dc-b367-85a57df3f825.png)

**Comment by thanisara-r** [comment]
@Th1nkK1D ใช้ text ว่า

ไม่พบการลงมตินี้ในเว็บไซต์

(อาจจะมีเคสที่จริงๆ อาจจะมีวาระลงมติ แต่เราไม่ได้เลือกมาลง  😅)

**Comment by Th1nkK1D** [comment]
Merged #32 with 5abb191
