### ISSUE TITLE
feat(/party/ชื่อพรรค): เพิ่ม sticky menu สำหรับข้าม section

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/they-work-for-us#36]
สืบเนื่องจาก #21 ทำให้หน้าของพรรคยาวมาก และคนอาจจะไม่รู้ว่ามี section อื่นๆ อยู่ด้านล่าง เลยจะเพิ่ม แถบ sticky สารบัญ

- เมื่ออยู่ในsectionนั้นๆ ลูกศรชี้ลงจะหายไป
- เมื่ออยู่ในsectionสมาชิก ลูกศรของแถบลงมติจะเปลี่ยนเป็นชี้ขึ้นแทน 

design ดูใน[figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=831%3A10326&t=TZD3n50ft44NsOZa-1)หน้า👥หน้า Profile กลุ่ม_feb2023
<img width="741" alt="CleanShot 2566-02-14 at 20 09 51@2x" src="https://user-images.githubusercontent.com/123941533/218748320-4bb19c4b-ee4b-405c-9f17-883d2b584659.png">

ตัวอย่างจาก([งานนี้](https://bkkelection2022.wevis.info/candidate/))

https://user-images.githubusercontent.com/123941533/218748563-fe1c839f-938a-4f45-8647-744d165e04a0.mp4

## Dev starting point

หน้านี้อยู่ที่ไฟล์ `src/templates/party-template.js` ครับ

**Comment by bothonachiz** [comment]
เดี๋ยวจัดการให้ครับ

**Comment by Th1nkK1D** [comment]
Merged #41

**Comment by Th1nkK1D** [comment]
@bothonachiz ฝากดู #57 ต่อได้ไหมครับ มันต่อเนื่องมาจาก issue นี้
