### ISSUE TITLE
feat(/party/ชื่อพรรค): เพิ่ม label ให้เห็นว่าคนนี้ย้ายพรรคมา ในหน้ารวมพรรค

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#43]
มีประวัติการย้ายพรรค เมื่อเทียบกับพรรคตอนเลือกตั้ง กี่พรรคไม่สน
![image](https://user-images.githubusercontent.com/54769527/221761718-63f381e7-efd9-4646-8c4c-5c01fbabae0e.png)

https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=966%3A6894&t=A7aCbmxRYcs7AIGM-4

**Comment by Th1nkK1D** [comment]
## Dev Starting point

Data is now available as described in #51 

Add a property in the GraphQL query and update UI

**Comment by Th1nkK1D** [comment]
Implemented in [4f964a0](https://github.com/wevisdemo/they-work-for-us/commit/4f964a00c741c66ae25d1e46f1fafa4041e05b07)
