### ISSUE TITLE
bug (/party/ชื่อพรรค): ข้อมูล About ของหน้าพรรคการเมืองไม่ขึ้นบนหน้าเว็บ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#45]
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/54769527/221765909-46253783-e35f-40e9-a06c-b09a2269bdbf.png">

ข้อมูลดึงได้จากชีท Parties คอลัมน์ Description

**Comment by GGolfz** [comment]
@thanisara-r Is that ok if I work on this issue?

**Comment by Th1nkK1D** [comment]
Merged #47
