### ISSUE TITLE
feat(/) แสดง ส.ส. ที่พ้นจากตำแหน่งบนเว็บในหน้ารวมพรรค แต่ไม่นับในจำนวนส.ส. ในสภา

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#46]
ตอนนี้ ส.ส. ที่ในฐานข้อมูล not active จะไม่แสดงบนหน้าเว็บ แต่ช่วงใกล้หมดสมัยสภา ส.ส. ลาออกเยอะมาก ทำให้เหลือข้อมูลน้อยมาก

ฝาก @namsaisup ดูเรื่องดีไซน์ด้วยค่ะ ตรงนี้จะแยกคนที่ยังมีตำแหน่ง กับพ้นตำแหน่งแล้วยังไงดี
![image](https://user-images.githubusercontent.com/54769527/222184761-bef4cc8e-80cf-46b0-8e14-751e98d7831a.png)

ส่วนหน้าบุคคล ไม่ต้องปรับ เพราะมีสถานะและผลโหวตอยู่แล้ว (ตัวอย่าง https://theyworkforus.wevis.info/people/อภิสิทธิ์-เวชชาชีวะ)

---

ส่วนอื่นที่ไม่ต้องเอาจำนวนคนที่พ้นตำแหน่ง (not active) มาคำนวณ
![image](https://user-images.githubusercontent.com/54769527/222184375-aa79d119-0e7c-44d2-b77e-1e3f7dfb2e65.png)
![image](https://user-images.githubusercontent.com/54769527/222184562-cc263778-e537-487d-90b9-f17ded5520c9.png)

**Comment by namsaisup** [comment]
การ์ดNot Active
- พื้นหลังสีเทา
- รูปโปรไฟล์มีรองพื้นสีดำ50% + "พ้นจากตำแหน่ง"
( ดูได้ใน [Figma](👥หน้า Profile กลุ่ม_feb2023) หน้า 👥หน้า Profile กลุ่ม_feb2023 )
<img width="631" alt="CleanShot 2566-03-02 at 20 24 31@2x" src="https://user-images.githubusercontent.com/123941533/222441539-0a67fd7d-deef-4b6f-a9eb-6ca41be44e33.png">

**Comment by Th1nkK1D** [comment]
# Dev starting point

`is_active` ของสส. จะบอกว่ายังอยู่ในตำแหน่งหรือเปล่า

เริ่มจาก `src/templates/party-template.js` ที่เป็นหน้าของพรรค
- เอา `is_active` filter จาก graphql query ออก
- ปรับ UI ของ `<PeopleCard />` ให้แสดงการพ้นจากตำแหน่ง (เคยย้ายพรรคไม่ได้อยู่ใน scope ของ issue นี้)

**Comment by bothonachiz** [comment]
เดี๋ยวจัดการให้ครับ 🫡

**Comment by Th1nkK1D** [comment]
Merged #49
