### ISSUE TITLE
bug(/): ภาพประกอบโดนดึงผิดสัดส่วนบน Safari

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/they-work-for-us#53]
![CleanShot 2566-03-22 at 09 56 08](https://user-images.githubusercontent.com/123941533/226793636-18743700-8d17-4dec-a48c-fc25e9b644a2.png)

**Comment by Th1nkK1D** [comment]
@namsaisup อันนี้ผมก็ไม่เจอ5555 browser อะไรนะครับ

**Comment by Th1nkK1D** [comment]
Fixed [847a615](https://github.com/wevisdemo/they-work-for-us/commit/847a6157c3ef9b06b7851684ba2a85b530f1e3dd)
