### ISSUE TITLE
bug: ภาพคน/โลโก้ในวงกลมทุกส่วนล้นขอบใน Safari

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/they-work-for-us#54]
![CleanShot 2566-03-22 at 10 00 24](https://user-images.githubusercontent.com/123941533/226794004-fcd4b88f-9f06-4f90-a108-8d8dfec24307.png)

**Comment by mixth** [comment]
Confirm the issue on Safari 16.3

Also found in the top page as well. 
![Screenshot 2566-03-22 at 5 14 20 PM](https://user-images.githubusercontent.com/6439183/226871794-c22d3ce4-c525-4e63-9bd8-1f522ce84bf5.png)

**Comment by Th1nkK1D** [comment]
# Dev starting point

คาดว่ามีปัญหาที่ component `PeopleAvatar` ซึ่งใช้ในหลายๆ หน้า

**Comment by Th1nkK1D** [comment]
Just check the issue with my old MacBook.
1. This issue exist in the current production website https://theyworkforus.wevis.info
2. I check the css. Somehow overflow hidden is not working in the `PeopleCard` component.

<img width="1254" alt="Screen Shot 2566-03-24 at 01 59 51" src="https://user-images.githubusercontent.com/8860448/227390160-ff1b784d-a9c1-4029-8698-af1075dba14d.png">

I tried a bit but honestly no idea how to fix this.

One interesting point. Actually, the overflow hidden is working for a few seconds after the page load, when the image is still blurry. But when it become sharper, the issue occur. This might have something to do with `GatsbyImage`? I address the deprecation of `GatsbyImage` and we should migrate it in the issue #39. It might help?

**Comment by Th1nkK1D** [comment]
Actually, if #8 is completed, this issue might be solved since we will use native image with URL from NocoDB

**Comment by Th1nkK1D** [comment]
#8 is  closed. The issue is  gone as expected.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/8860448/227524977-3a75711c-175b-4069-8694-6ab315c9171a.png">
