### ISSUE TITLE
feat: เปลี่ยนโลโก้บน Navbar

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/they-work-for-us#55]
![CleanShot 2566-03-22 at 09 58 58](https://user-images.githubusercontent.com/123941533/226794339-62e725e1-5264-405b-8fe3-f3144dd55c6b.png)

Expectation :
![CleanShot 2566-03-22 at 10 24 11](https://user-images.githubusercontent.com/123941533/226794370-e51af49b-1c70-49aa-9e0e-da7d86d27cc0.png)

**Comment by Th1nkK1D** [comment]
Implemented in [026fd8f](https://github.com/wevisdemo/they-work-for-us/commit/026fd8ff17d296033839ae7f94ea6ff3ab19a56b)
