### ISSUE TITLE
feat(/party): เติม Drop Shadow ที่navในหน้าโปรไฟล์พรรค

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/they-work-for-us#57]
![CleanShot 2566-03-22 at 09 59 50](https://user-images.githubusercontent.com/123941533/226795426-1ec4003f-0efd-4475-a8c0-d6c2bfe5118c.png)

### Expectation :

![CleanShot 2566-03-22 at 10 35 05](https://user-images.githubusercontent.com/123941533/226795582-c1378090-c068-469f-b493-c7153efaed01.png)

**Comment by Th1nkK1D** [comment]
#79 merged
