### ISSUE TITLE
[Bug safari mobile] no padding

### ISSUE THREAD

**Issue by wasdee** [wevisdemo/they-work-for-us#59]
I'm not sure if this is intended. 
But the text has no padding. 
![image](https://user-images.githubusercontent.com/8089231/227246331-2404d665-b7d9-4b93-bc86-9829fb986df1.png)

**Comment by Th1nkK1D** [comment]
I can reproduce it in Chrome and it should be fixed in 556bb723f47cd2e934abc0476fca31995b6d512a. Can you recheck the issue on staging?

**Comment by wasdee** [comment]
Visual confirmed, Fixed
