### ISSUE TITLE
feat(/): เพิ่ม Search ชื่อ ส.ส. ในหน้าแรก

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/they-work-for-us#6]
อยากให้หาว่า “ส.ส. เขตบ้านฉันคือใคร?” ได้ง่ายๆ หน่อย

**Comment by thanisara-r** [comment]
อัพเดทดีไซน์แล้ว ดูในนี้ [Figma]( https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=601%3A4009)

**Comment by rootEnginear** [comment]
ยังต้องการให้หาด้วยรหัสไปรษณีย์อยู่ไหมคะ

**Comment by rootEnginear** [comment]
ตอนนี้ต้องการให้ค้นหาด้วยอะไรแทนไหมคะ เห็น Issue ใน Figma เกี่ยวกับรหัสไปรษณีย์แล้วค่ะ

**Comment by thanisara-r** [comment]
ค้นด้วยรหัสไปรษณีย์ตาม Figma ค่ะ ส่วนข้อมูล รหัสไปรษณีย์-เขตเลือกตั้ง-ชื่อ ส.ส. ใช้จากอันนีได้ไหม? https://github.com/electinth/dataset-election-62-candidates/tree/master/data

หรือมันควรหาที่ใส่ใน DataSheet เพราะบางเขตเปลี่ยนคนไปแล้ว ปรึกษา @Th1nkK1D ด้วยค่า

**Comment by Th1nkK1D** [comment]
> ค้นด้วยรหัสไปรษณีย์ตาม Figma ค่ะ ส่วนข้อมูล รหัสไปรษณีย์-เขตเลือกตั้ง-ชื่อ ส.ส. ใช้จากอันนีได้ไหม? https://github.com/electinth/dataset-election-62-candidates/tree/master/data
> 
> หรือมันควรหาที่ใส่ใน DataSheet เพราะบางเขตเปลี่ยนคนไปแล้ว ปรึกษา @Th1nkK1D ด้วยค่า

เท่าที่ลองคิดดูยากอยู่ครับถ้าจะทำ postcode คือเราต้องมีข้อมูล 2 ชุด
- ใน people sheet เรามี mp_province กับ mp_zone อยู่แล้ว แค่ต้อง recheck ว่าตรงนี้ update เรื่อยๆก็โอเคครับ
- ชุดข้อมูลที่เชื่อมรหัสไปรษณีกับเขตเลือกตั้งของจังหวัดนั้น ตรงนี้ต้องทำใหม่ทุกครั้งที่เลือกตั้งใหม่ ผมยังไม่เจอข้อมูล postcode จากลิ้งที่พี่ส่งมา แต่มีความพยายามในการอธิบายเขตเลือกตั้งไว้ใน [ection-zones.json](https://github.com/electinth/dataset-election-62-candidates/blob/master/data/election-zones.json) ซึ่งมันซับซ้อนมาก มันไม่ได้แบ่งเขตสวยๆ (อย่างงาน election simulation ที่ผมทำ เรายอมบอกชื่อเขตของแต่ละเขตเลือกตั้งในกรุงเทพเท่านั้น ทำต่างจังหวัดไม่ไหว) มีความเสี่ยงในการเลือกตั้งปีหน้าด้วยฮะว่า จะได้ข้อมูลมาแบบไหน

ก็เลยเสนอ solution ที่ง่ายกว่านั้น แต่ไม่รู้ว่าจะ useful แค่ไหน คือเราแค่ search จังหวัดแทน postcode แล้วในหน้า result เราแสดง สส. ทั้งหมดในจังหวัด group ตามเขตเลือกตั้งที่บอกเป็นเลขไปเลย เช่น

```
ส.ส. จากกรุงเทพ

เขตเลือกตั้ง 1
- นาย a
- นาย b

เขตเลือกตั้ง 2
- นาย c
```
ในเคสนี้คือข้อมูลพร้อมทำได้เลย

ปล. จากรูปข้างล่าง ผมอ่านแล้วยังงงอะ5555 ปวดหัวประเทศไทย คือเลือก postcode แล้วก็ยังงงว่าคนไหนที่เราเลือกไปนะ postcode อาจจะไม่ได้เวิร์คขนาดนั้น ถ้าทำปบบจังหวัดก็คงไม่ต้องมีส่วนนี้ในการ์ด

![image](https://user-images.githubusercontent.com/8860448/201938505-fb6a2149-18de-45a3-849e-8d27d5670c89.png)

ไม่รู้ผมตกหล่นอะไรไปไหมนะครับ

**Comment by thanisara-r** [comment]
ปัญหาหลักคือ คนไม่รู้ว่าตัวเองอยู่เขตเลือกตั้งเลขที่เท่าไหร่ ดังนั้นการให้เลือกจากเลขที่ของเขตเลือกตั้งอย่างเดียว ก็ไม่ user-friendly ค่า
คิดว่าต่อให้เสิร์ชจากจังหวัด ก็น่าจะต้องวงเล็บ `ชื่อเขต/อำเภอ+ยกเว้น/เฉพาะพื้นที่` อยู่ดีอ่า
คำถามคือ ควรเพิ่มวงเล็บ `ชื่อเขต/อำเภอ+ยกเว้น/เฉพาะพื้นที่` ไว้ตรงไหนของข้อมูลดี

**Comment by Th1nkK1D** [comment]
> ปัญหาหลักคือ คนไม่รู้ว่าตัวเองอยู่เขตเลือกตั้งเลขที่เท่าไหร่ ดังนั้นการให้เลือกจากเลขที่ของเขตเลือกตั้งอย่างเดียว ก็ไม่ user-friendly ค่า คิดว่าต่อให้เสิร์ชจากจังหวัด ก็น่าจะต้องวงเล็บ `ชื่อเขต/อำเภอ+ยกเว้น/เฉพาะพื้นที่` อยู่ดีอ่า คำถามคือ ควรเพิ่มวงเล็บ `ชื่อเขต/อำเภอ+ยกเว้น/เฉพาะพื้นที่` ไว้ตรงไหนของข้อมูลดี

เข้าใจละครับ ถ้างั้นผมสงสัยว่าทำไมถึงอยากให้ search ด้วย postcode มากกว่าการ search ชื่อ เขต/อำเภอไปเลยนะ เพราะ 1 postcode เหมือนจะมีได้หลายเขต เสิร์ชเขต/อำเภอ ไปเลยน่าจะตรงกว่า (postcode ก็ทำได้ครับ ต้องไปหา data ที่โยงเขตกับ postcode เพิ่ม)

ที่ยากตอนนี้คือ 1 เขต/อำเภอ != 1 เขตเลือกตั้ง เพราะเขคเลือกตั้งซอยระดับแขวงได้ด้วย หมายความว่าถ้าเสิร์ชก็อาจจะเจอมากกว่า 1 เขตเลือกตั้ง แล้วต้องนั่งอ่านอีกทีนึงว่าของเราเขตไหน อันนี้ผมเข้าใจถูกใช่ไหมครับ

ถ้าเรา concern แค่ปีนี้ก่อน ไฟล์ [election-zones.json](https://github.com/electinth/dataset-election-62-candidates/blob/master/data/election-zones.json) เพียงพอเลยครับ แต่ว่าต้องมานั่งทำความเข้าใจแล้วเช็คเคสแปลกๆหน่อย มีโอกาสที่ PM ไม่ต้องกรอกอะไรเองเพิมเติมเลย

คำถามผมคือตัวข้อมูลตรงนี้จำเป็นต้อง available กับ PM ไหมครับ PM ต้องเข้ามาแก้อะไรด้วยได้ไหม ถ้าไม่เราก็เก็บไฟล์นี้ไว้ใน code ของเราเลย แล้วปีหน้าค่อยมาว่ากันใหม่ เพราะเรายังไม่รู้ว่าจะได้ข้อมูลมาหน้าตาประมาณไหน

**Comment by thanisara-r** [comment]
- ที่ให้ใส่รหัสไปรษณีย์ เพราะกลัวคนพิมพ์ชื่อผิด (เคยเทสต์ตอน 62 แล้วคนใส่เลขง่ายกว่า) แต่ส่วนไม่ติดถ้าจะเป็น เขต/อำเภอ 
- 1 เขต/อำเภอ != 1 เขตเลือกตั้ง ตามที่เข้าใจค่า ก็จะมีย่อยลงไป เช่น เขตหนองแขม ก็ต้องเลือกก่อนว่าอยู่ในแขวงหนองแขมไหม
<img width="404" alt="image" src="https://user-images.githubusercontent.com/54769527/213076209-08fbbfd1-4dc3-4c60-a42e-86c75fbe14d9.png">
- PM ไม่จำเป็นต้องเห็นหรือแก้ได้ค่ะ

**เพิ่มเติม** หลังการเลือกตั้ง 66 จะมีเขตเลือกตั้งใหม่ เดี๋ยวคุยกับดีไซเนอร์เรื่องวิธีเสิร์ชแล้วมาอัพเดทอีกทีค่ะ

**Comment by thanisara-r** [comment]
@namsaisup ช่วยอัพเดท Design ให้ด้วยค่ะ

**Comment by namsaisup** [comment]
อัพเดทดีไซน์เป็นการค้นด้วยชื่อเขต/อำเภอแทนแล้วค่ะ 
ดูใน [figma](https://www.figma.com/file/42QVt123mfeM0XgT9ACRz1/TheyWorkForUs_WebsiteUpdate?node-id=831%3A6803&t=tx5cPh0I6Qp3DhFu-1) หน้า 🔍 เพิ่มsearchชื่อสส_feb2023

<img width="1063" alt="CleanShot 2566-01-30 at 18 50 21@2x" src="https://user-images.githubusercontent.com/123941533/215469580-991bb16e-ad50-47a9-b84b-a511bd60c149.png">

**Comment by Th1nkK1D** [comment]
## Dev starting point
- ใช้ไฟล์ [election-zones.json](https://raw.githubusercontent.com/electinth/dataset-election-62-candidates/master/data/election-zones.json) เป็นข้อมูลหลักของการโยงเขตเลือกตั้ง แนะนำให้ download มาใส่ `src/content` ซึ่งเป็นโฟลเดอร์ที่เก็บข้อมูล แนะนำให้ใช้ graphql ตามสไตล์ Gatsby หรือถ้ายากไป import JSON ตามปกติก็ได้ครับ
- เพื่ม search bar ในหน้า home `src/pages/index.js` ข้อมูลที่จะถูกเอามาแสดงใน popup เรามี `allPeopleYaml` ที่ถูก query ออกมาจาก graphql อยู่แล้ว อาจจะต้องลองเช็คว่าเพียงพอไหมหรือต้อบง query อะไรมาเพิ่มครับ

![image](https://user-images.githubusercontent.com/8860448/215745684-1b786549-3202-4c69-9643-cb282a4ff9d0.png)

**Comment by heyfirst** [comment]
Technical Note:
- Search
  - ใช้ อำเภอ + จังหวัด ค้นหาเขตเลือกตั้ง (zones) มีสิทธิที่ zones จะมีมากกว่า 1 เขต
  - ใช้ จังหวัด + เขตเลือกตั้ง ค้นหา ส.ส. ต่อ
- Data preparation
  - ใช้  [election-zones](https://raw.githubusercontent.com/electinth/dataset-election-62-candidates/master/data/election-zones.json) 15.2kB ในการหา zones
  - ใช้ [people.yaml](https://github.com/wevisdemo/they-work-for-us/blob/master/src/contents/people.yaml) ในการหาคน
  - อาจจะต้อง clean people.yaml ให้เหลือแค่ สส ที่มีเขตเลือกตั้งจริง ๆ เอาคนอื่นออกให้หมด เอา field ไม่สำคัญออกไปด้วย
  - zones กับ people อาจจะต้อง fetch ผ่าน frontend ได้

**Comment by heyfirst** [comment]
ผมทำ demo มานำเสนอ แต่มันยังไม่ accurate .. ผมลองทำแบบ search เร็วๆ ที่พิมพ์แล้วชื่อขึ้นมาแบบ real time ได้เลย เพราะข้อมูลเขตเลือกตั้ง สส ไม่เยอะมากขนาดนั้นครับ ... ผมยังไม่ได้ปรับตาม design 

https://user-images.githubusercontent.com/4945174/216846987-0e85f135-b130-4cfd-b0f3-e78110982d96.mov

จาก demo นี้
- มีแค่ สส ประจำเขตที่ยังดำรงตำแหน่งของแต่ละเขตอยู่ เอาข้อมูลสสคนอื่นออกหมดแล้วคับ (ข้อมูลที่จำเป็นทั้งหมดใช้แค่ 157kB, โหลดไม่ถึงเสียววิก็เสร็จแล้ว)
- ตัว search จะใช้วิธีเทียบจากอำเภอ/เขตเป็นหลัก รองลงมาจะใช้จังหวัด ถ้าอันไหน match กว่าจะก็ใช้ข้อมูลตัวนั้นอยู่บนสุด
- ยังมีส่วนที่ปรับปรุงได้เช่น
  - ผมสามารถให้ตอนพิมพ์ มี dropdown ลงมาจากช่อง inbox ได้เลย เป็นเหมือนใน design ด้านบน
  - ในขณะเดียวกัน ตอนพิมพ์ ก็ list ชื่อ สส แบบ realtime แบบนี้ได้เช่นกัน ผู้ใช้จะได้ไม่ต้องกด enter เพื่อดูข้อมูลเลย
  - ผมเชียร์เปลี่ยนจาก modal เป็นทำหน้าใหม่ โดยเริ่มจากตัว search จากเขตเลือกตั้งอันนี้ หลังจากนั้นเราต่อยอดหน้านั้น ให้สามารถ search ข้อมูลอื่น ๆ ได้อีกในอนาคตครับ (ผมลองค้นดูว่าเคยมีแนวคิดจะทำ search อยู่เมื่อก่อน https://github.com/electinth/politician-directory/issues/10)

ลองเล่นได้ที่นี่ฮะ https://codesandbox.io/embed/jovial-joliot-9hv7uc?fontsize=14&hidenavigation=1&theme=dark

cc. @Th1nkK1D

**Comment by Th1nkK1D** [comment]
@heyfirst ไปคิดๆ มา มีประเด็นประมาณนี้

>   * ผมสามารถให้ตอนพิมพ์ มี dropdown ลงมาจากช่อง inbox ได้เลย เป็นเหมือนใน design ด้านบน
>   * ในขณะเดียวกัน ตอนพิมพ์ ก็ list ชื่อ สส แบบ realtime แบบนี้ได้เช่นกัน ผู้ใช้จะได้ไม่ต้องกด enter เพื่อดูข้อมูลเลย

นึกได้ว่า autocomplete เป็นข้อมูลสส.ไปเลยมันไม่เหมาะสำหรับ mobile เพราะมันมีที่ให้แสดงข้อมูลน้อยมากๆ คิดว่าอันนี้คงไว้แบบเดิมสมเหตุสมผลกว่า 

>   * IMHO 🙇🏻‍♂️ ผมเชียร์เปลี่ยนจาก modal เป็นทำหน้าใหม่ โดยเริ่มจากตัว search จากเขตเลือกตั้งอันนี้ หลังจากนั้นเราต่อยอดหน้านั้น ให้สามารถ search ข้อมูลอื่น ๆ ได้อีกในอนาคตครับ (ผมลองค้นดูว่าเคยมีแนวคิดจะทำ search อยู่เมื่อก่อน [Create search popup UI electinth/politician-directory#10](https://github.com/electinth/politician-directory/issues/10))

ส่วนขึ้นหน้าใหม่เพื่อเพิ่ม function search ที่หาอย่างอื่นได้ด้วยเนี่ย ไว้สร้าง issue ใหม่เลย ขอบอกว่า @thanisara-r อยากได้มาหลายปีแล้ว55555 แต่ในเคสนี้ ไม่ได้มี strong opinion รู้สึกว่าจะแสดง popup ก็ได้ (ง่ายตรงไม่ต้องส่งข้อมูลระหว่างหน้า) หรือจะแสดงผลในหน้าใหม่ไปเลยก็ได้ (ดีที่ไม่ต้องโหลดข้อมูลืั้งหมดในหน้าแรก)

อีกคำถามนึงคือ @heyfirst จะทำ issue นี้ในส่วนไหนบ้างนะ หมีพูห์ถามๆ อยู่ว่ามี issue ให้ช่วยไหม ถ้าอยากส่งต่อก็บอกมาได้ว่าจะทำถึงตรงไหน

**Comment by heyfirst** [comment]
@Th1nkK1D ส่งต่อเลยได้ป่าว เด่วไปทำหน้า search ให้เลย (พี่สร้าง issue ให้ผมด้วย) ขอผมสิ้นเดือนได้หน้า search ทั้งเว็บได้เลย เร็วพอ ๆ Algolia ด้วย

**Comment by heyfirst** [comment]
แล้วก็ยังไม่ต้องทำ design ให้ก็ได้ เกรงใจ กลัวเสียเวลา เด่วทำ playable page ให้ก่อน แล้วหลังจากนั้นดูว่า search ทำไรได้บ้าง แล้วค่อยไปคิด design ทีหลังง

**Comment by Th1nkK1D** [comment]
@heyfirst เบาก่อนหนุ่ม เย็น55555 เค้าเสนองี้
1. สำหรับ issue นี้เตรียม function ไว้ 2 อันได้ไหม จะได้เอาไปทำ UI ต่อได้เลย ตอนนี้มันครึ่งๆ กลางๆ
    - function ที่ใส่ keyword แล้วคืน array ของ อำเภอ+จังหวัด สำหรับ auto complete
    - function ที่ใส่ อำเภอ+จังหวัด ที่ได้จากฟังชั่นแรก แล้วคืน array ของ object ข้อมูลสส.ที่อยู่ใน ของอำเภอ+จังหวัด นั้นๆ
2. สำหรับเรื่อง search ที่จะแยก issue มันพอมีไอเดียและดีไซน์ ที่คุยๆ กันในทีมอยู่ ขอไปตกลงให้ solid ก่อนดีกว่า ให้ requirement ชัดแล้วจะทักไป เดี๋ยวทำไว้แล้วไม่ได้ใช้จะเสียของเอา ไม่ต้องเกรงใจ

**Comment by heyfirst** [comment]
🫡 you got my word! ถ้าทำได้ช้าสุด วันเสาร์หน้าจะช้าไปไหม? วีคนี้หนักอยู่ ติดงานที่บริษัท แต่ถ้าเสร็จก่อนจะรีบทำให้

**Comment by Th1nkK1D** [comment]
@heyfirst สบายยยย ไม่ต้องกดดัน ขอบคุณมากที่มาช่วย 🫡

**Comment by MEEP00H** [comment]
รับมาดู ui ต่อครับ

**Comment by Th1nkK1D** [comment]
> รับมาดู ui ต่อครับ

You are good to go now! @heyfirst work is now merged into the branch `feat/search-people-by-zones`. More information can be found on the PR #38

**Comment by heyfirst** [comment]
@MEEP00H 🙇🏻 do you want bubble tea? it can be sent to your condo as a gift naaaaa

**Comment by Th1nkK1D** [comment]
อันนี้เวอร์ชั่นที่พูห์ทำมาฮะ มีเรื่องอยากปรึกษา @namsaisup นิดหน่อยครับ

https://user-images.githubusercontent.com/8860448/221600043-01084728-9b6d-43f7-bf0a-d6c8367bcadf.mp4

1. จริงๆ แล้วปุ่นค้นหาไม่จำเป็นไหมนะ เพราะพอเราเลือกเขตใน dropdown แล้วเปิด popup เลยก็ได้ ไม่ต้องกดค้นหาเพิ่มอีกที หรือมีอะไรที่ผมลืมคิดไหมนะ
2. ผมว่า popup มันจมไปแฮะ แยกออกจาก content ข้างหลังยาก เราควร dim พื้นหลังให้มืดลงแล้วเพิ่ม shadow ให้ดูลอยขึ้นมาดีไหมนะ อะไรประมาณนี้
![image](https://user-images.githubusercontent.com/8860448/221601395-62b60f20-88b3-437a-a9f4-d0a4fa1813d7.png)

@MEEP00H ระหว่างรอ feedback พี่จั๊ก เม้นไปใน PR นิดหน่อยเรื่องโค้ด แล้วตอนนี้ item ใน dropdown มัน align center อะ อยากให้ปรับเป็น align left ตาม design เพราะมันอ่านง่ายกว่า (จากวีดีโอ Opera ขึ้น scrollbar ให้ popup เฉย แต่ถ้า browser อื่นไม่เป็นไรมั๊ง)

**Comment by namsaisup** [comment]
@Th1nkK1D @MEEP00H เห็นด้วยค่า แก้แระ
1. เปลี่ยนปุ่มเป็นแค่icon
<img width="793" alt="CleanShot 2566-02-28 at 09 30 26" src="https://user-images.githubusercontent.com/123941533/221738130-37dd3102-e0c2-423f-8fae-34ccbcc51dd8.png">
2. รองพื้นหลังดำ60%
<img width="1276" alt="CleanShot 2566-02-28 at 09 32 10@2x" src="https://user-images.githubusercontent.com/123941533/221738268-8555cc0b-c022-421c-8f77-7c4e7b52780a.png">

**Comment by Th1nkK1D** [comment]
Merged #42 กราบขอบพระคุณทุกคนครับ
