### ISSUE TITLE
[Bug safari mobile] elements should be fill to leftmost

### ISSUE THREAD

**Issue by wasdee** [wevisdemo/they-work-for-us#60]
![image](https://user-images.githubusercontent.com/8089231/227247352-b0678f58-fe8e-4394-a2b6-892a2aa8e3f5.png)
![image](https://user-images.githubusercontent.com/8089231/227247537-5b833706-15aa-41c4-9fdc-d258adc719ab.png)

**Comment by Th1nkK1D** [comment]
I can reproduce it in Chrome and it should be fixed in 85569431125ba5498cd381455d87fd6d0575dc05. Can you recheck the issue on staging?

**Comment by wasdee** [comment]
Visual confirmed in Safari Mobile, Fixed
