### ISSUE TITLE
 feat(/): เพิ่มวันที่อัพเดตข้อมูลในหน้าแรก

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#63]
<img width="1424" alt="Screenshot 2566-03-24 at 9 47 13 AM" src="https://user-images.githubusercontent.com/54769527/227411763-e8a73968-b1c0-42d1-b45a-2327b858f905.png">

**Comment by mixth** [comment]
@Th1nkK1D วันที่นึ้ เราควรใช้วันไหนดีครับ กำลังคิดว่าเป็นวันที่ build ได้ไหมครับ

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D วันที่นึ้ เราควรใช้วันไหนดีครับ กำลังคิดว่าเป็นวันที่ build ได้ไหมครับ

ผมคิดว่าได้นะครับ ตรงไปตรงมาดี

**Comment by Th1nkK1D** [comment]
implemented in 53e26459204a1dc64a9cb6d2e28d86ed63942811
