### ISSUE TITLE
bug (/votelog/): หน้าผลการลงมติ chart รายคน ขึ้นว่า 'พ้นจากตำแหน่ง' ทุกคน (Status ผิด)

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#64]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/54769527/227413644-c71a406a-d0c4-4ba0-8520-0fddad13913a.png">
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/54769527/227413673-3acda3b1-890d-4fcb-9e9a-624b765c792b.png">

**Comment by Th1nkK1D** [comment]
This should be the same case with #58 just in a difference place.
