### ISSUE TITLE
bug (/votelog/): หน้าผลการลงมติที่เป็นประชุมร่วมสองสภา ส่วนที่เป็น ส.ว. ไม่มี icon + ลิงก์ไปหน้าที่เป็น Not Found

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#65]
<img width="915" alt="Screenshot 2566-03-24 at 10 05 44 AM" src="https://user-images.githubusercontent.com/54769527/227414083-d62df72a-805c-4a4b-88d7-3c20cc2b2cb3.png">

@namsaisup มี icon ส.ว. ไหม?

กดแล้ว ตอนนี้ลิงก์ไป Not Found แต่จริงๆ ต้องลิงก์ไป https://staging.theyworkforus.wevis.info/senate/

**Comment by namsaisup** [comment]
ไฟล์อยู่ในนี้นะ https://drive.google.com/file/d/1xngX138Ldg4Vnd_rRqFrRJXav4tD6Cqs/view?usp=sharing
<img width="107" alt="CleanShot 2566-03-24 at 17 27 16@2x" src="https://user-images.githubusercontent.com/123941533/227496927-6e5eb263-34ea-4261-85e7-9cecaef28240.png">

**Comment by mixth** [comment]
@namsaisup เหมือนลิ้งค์ที่ให้จะใช้ไม่ได้แล้วครับ ขึ้นว่าอยู่ใน trash ครับผม

**Comment by namsaisup** [comment]
@mixth ลืมไปว่าย้ายโฟลเดอร์ ไฟล์อยู่ในนี้แทนนะคะ
https://drive.google.com/file/d/1jNvkQumia0E7T4wnzy6XDW2Bqas_ZraL/view?usp=sharing
