### ISSUE TITLE
bug (/votelog/): การ์ดหน้าสรุปผลการลงมติ ข้อมูลไม่ตรงกับหน้ารายละเอียด

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#66]
<img width="460" alt="Screenshot 2566-03-24 at 10 10 23 AM" src="https://user-images.githubusercontent.com/54769527/227414662-846a8ea1-57bf-410e-bdb8-f82a21df3951.png">
<img width="916" alt="Screenshot 2566-03-24 at 10 10 04 AM" src="https://user-images.githubusercontent.com/54769527/227414665-cedd3171-ee19-4907-9d11-d649459be040.png">

**Comment by mixth** [comment]
ผม reproduce สิ่งนี้บน staging ไม่ได้ครับ

กำลังเดาว่าเป็นที่ data + caching ระหว่างสองหน้านี้หรือเปล่าครับ
(เคย deploy และ cache หน้าแรกไว้ตอน 21/11/27/0)

### Screenshot ล่าสุดบน staging
<img width="450" alt="Screenshot 2566-03-25 at 3 11 10 PM" src="https://user-images.githubusercontent.com/6439183/227705678-50dc089c-a475-4aa0-9f1d-0b2667a71927.png">
<img width="894" alt="Screenshot 2566-03-25 at 3 11 41 PM" src="https://user-images.githubusercontent.com/6439183/227705682-506c5ab0-1341-425e-b741-139c13549ef8.png">
