### ISSUE TITLE
 feat(/): เพิ่ม ตำบล (สำหรับจังหวัดอื่นๆ) /แขวง (สำหรับกรุงเทพ) ไว้ในลิสต์ตัวเลือกด้วย

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/they-work-for-us#78]
![image](https://user-images.githubusercontent.com/54769527/232412608-927a8219-9720-4c5a-a348-b04f65a691f8.png)

เพิ่ม ตำบล (สำหรับจังหวัดอื่นๆ) /แขวง (สำหรับกรุงเทพ) ไว้ในลิสต์ตัวเลือกด้วย เพราะบางจังหวัดมี อำเภอ/เขต เดียวกัน แต่แบ่งกันที่ตำบล/แขวง+ เทศบาลก็มี

ตัวอย่างจากงาน https://github.com/wevisdemo/thailand-election-2023/tree/main/apps/yourcandidates

![image](https://user-images.githubusercontent.com/54769527/232413669-63f44df0-2437-435c-9735-d37db35b45bd.png)

**Comment by bothonachiz** [comment]
🙌

**Comment by bothonachiz** [comment]
จากที่ผมไล่ดู data เราสามารถใช้ district_province_list.json ใน yourcandidates มาเป็น options ได้

แต่ข้อมูล zones.json จะไม่สามารถ map กลับไปหา option ที่เลือกได้เพราะในไฟล์ zone.js ขาดตำบลที่ใช้ในการ map กลับไปครับ 

ไม่แน่ใจว่ามีไฟล์ข้อมูล ส.ส. ปัจจุบันที่ระบุตำบลไหมครับ

**Comment by Th1nkK1D** [comment]
@bothonachiz จริงๆ แนะนำให้ไปดู 2 PR ที่เคย implement feature นี้ก่อนที่จะมีแขวง/อำเภอครับ #6 
1. reshape json จาก [dataset-election-62-candidates](https://github.com/electinth/dataset-election-62-candidates/blob/master/data/election-zones.json) เตรียมไว้ #38 
2. เอาข้อมูลจากอันแรกมาทำ UI #42

ผมคิดว่าไม่ต้องเริ่มจาก 0 เพราะ logic ส่วนใหฐ่เหมือนเดิม แล้วเพิ่ม แขวง/ตำบลเข้าไป น่าจะง่ายกว่า

**Comment by Th1nkK1D** [comment]
#83 merged
