### ISSUE TITLE
admin: เพิ่มรูป ส.ส. ใหม่/พรรคใหม่เองได้

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/they-work-for-us#8]

**Comment by thanisara-r** [comment]
@Th1nkK1D ส่วนนี้น่าจะไม่เกี่ยวกับ Design ไหมคะ? แต่หมายถึงการดึงข้อมูลจากหลังบ้าน

ปัจจุบันการเพิ่มพรรคหรือคนใหม่ ใน Data Sheet ไม่มีที่ให้ใส่รูป และไม่รู้ตอนนี้รูปคน+โลโก้ดึงมาจากไหน ทำอย่างไรให้ non-dev เพิ่มสิ่งนี้ได้

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D ส่วนนี้น่าจะไม่เกี่ยวกับ Design ไหมคะ? แต่หมายถึงการดึงข้อมูลจากหลังบ้าน
> 
> ปัจจุบันการเพิ่มพรรคหรือคนใหม่ ใน Data Sheet ไม่มีที่ให้ใส่รูป และไม่รู้ตอนนี้รูปคน+โลโก้ดึงมาจากไหน ทำอย่างไรให้ non-dev เพิ่มสิ่งนี้ได้

ใช่แล้วครับบบบ เป็นเรื่องของ internal tools หลังบ้านว่าจะให้ nondev จัดการรูปภาพพรรคและคนยังไง

**Comment by thanisara-r** [comment]
เสนอวิธี
1. มีที่อัพโหลดรูปเพื่อสร้าง url
2. ใส่ url ลงใน Data Sheet

**Comment by Th1nkK1D** [comment]
เริ่มคิดว่าเราสามารถใช้ nocodb ไปเลยได้ครับ เพราะมันอัพรูปใส่ตารางได้ ซึ่งไม่ใช่แค่รูป ผมว่าถ้าเราจัดระบบตารางใหม่ nocodb จะเป็น single source of truth ของ Thai politics data ที่ WeVis curate ได้เลย

**Comment by Th1nkK1D** [comment]
Data พร้อมแล้วจาก #51 เหลือต้องปรับ code frontend มาใช้ `images[0].url`

**Comment by Th1nkK1D** [comment]
Implemented in [2883cef](https://github.com/wevisdemo/they-work-for-us/commit/2883cefbeab75253a613f248ab112ac61f939f21)
