### ISSUE TITLE
bug: แสดงข้อมูล Quote ผิด 

### ISSUE THREAD

**Issue by AlaweeWme** [wevisdemo/they-work-for-us#85]
## อธิบายคร่าวๆ ว่าเกิดอะไรขึ้น
เจอโควทคำพูดในเว็บผิด 
- [ถ้าผมจะกล่าวบ้างว่า ผู้อภิปรายเป็นส.ส.ขี้ข้าโจร...]
- ที่แสดงในเว็บ คือ ส.ส. กิตติศักดิ์ คณาสวัสดิ์ (ไม่ได้เป็นคนพูด) 
- คนพูดคือ ส.ว. กิตติศักดิ์ รัตนวราหะ

…

## วิธีที่ทำให้เกิดบั๊ก

1. ไปที่ [Link](https://theyworkforus.wevis.info/people/%E0%B8%81%E0%B8%B4%E0%B8%95%E0%B8%95%E0%B8%B4%E0%B8%A8%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%B4%E0%B9%8C-%E0%B8%84%E0%B8%93%E0%B8%B2%E0%B8%AA%E0%B8%A7%E0%B8%B1%E0%B8%AA%E0%B8%94%E0%B8%B4%E0%B9%8C/?fbclid=IwAR3K1ZWbURtLKB_MKDD5MUYcJp7f5Qqdl_jzSrDxuwjpYd2SgsFqeANwIJQ)  
2. เลื่อนไปที่โควตคำพูด …
3. จะเจอว่า …ถ้าผมจะกล่าวบ้างว่า ผู้อภิปรายเป็นส.ส.ขี้ข้าโจร...

## สิ่งที่ถูกต้องควรเป็นอย่างไร
ตัดโควทคำพูดออก ไม่แสดงบนหน้าเว็บ
…

## สิ่งที่เกิดขึ้นจริงคือ
ตามรูปข้างล่างครับ
…

## ภาพ/วิดีโอ (ถ้ามี)
![Screenshot (71)](https://user-images.githubusercontent.com/132883133/236783037-c44debe9-1076-42d2-afb8-942a2c57982e.png)
![Screenshot (70)](https://user-images.githubusercontent.com/132883133/236783030-213b88a5-4255-44cb-a614-4e1eae264be3.png)

…

## อุปกรณ์ที่ใช้

- [x] คอมพิวเตอร์
  - [x] Windows
  - [ ] MacOS
  - [ ] Linux
- [ ] มือถือ/แท็บเล็ต
  - [ ] Android
  - [ ] iOS
  - [ ] iPadOS

ถ้าไม่มีในลิสต์ โปรดระบุ: …

## เบราเซอร์

- [x] Chrome, MS Edge Chromium (หรือเบราเซอร์อื่นที่ใช้ Chromium)
- [ ] Firefox
- [ ] Safari

ถ้าไม่มีในลิสต์ โปรดระบุ: …

## มีอะไรเพิ่มเติมไหม

…

**Comment by Th1nkK1D** [comment]
implemented in 64255307ff3aa43087cff994cad9400b5bd55796
