### ISSUE TITLE
bug: ค้นหาชื่อมติเป็น case sensitive

### ISSUE THREAD

**Issue by napatswift** [wevisdemo/they-work-for-us#87]
## อธิบายคร่าวๆ ว่าเกิดอะไรขึ้น
พยายามหามติที่มี `SME` แต่พิมพ์ `sme` แล้วไม่เจอ

<img width="615" alt="Screenshot 2566-07-06 at 09 51 52" src="https://github.com/wevisdemo/they-work-for-us/assets/26627006/30327038-2c94-43e7-86dc-99710f4455eb">

แต่เจอเมื่อพิมพ์ `SME`

<img width="952" alt="Screenshot 2566-07-06 at 09 53 27" src="https://github.com/wevisdemo/they-work-for-us/assets/26627006/95e90a85-fb58-47f3-b9a1-fa56d0007ee4">

## วิธีที่ทำให้เกิดบั๊ก

1. ไปที่[นี่](https://theyworkforus.wevis.info/votelog/)
2. ค้นหา `sme` และ ค้นหา `SME`

## อุปกรณ์ที่ใช้

- [x] คอมพิวเตอร์
  - [ ] Windows
  - [x] MacOS
  - [ ] Linux
- [ ] มือถือ/แท็บเล็ต
  - [ ] Android
  - [ ] iOS
  - [ ] iPadOS

ถ้าไม่มีในลิสต์ โปรดระบุ: …

## เบราเซอร์

- [x] Chrome, MS Edge Chromium (หรือเบราเซอร์อื่นที่ใช้ Chromium)
- [ ] Firefox
- [x] Safari

**Comment by Th1nkK1D** [comment]
fixed in 2dc7b1c9ec821d19be583e7dd7a023e3b3e3bbef

![image](https://github.com/wevisdemo/they-work-for-us/assets/8860448/cc64ac40-0c9c-450b-92be-ce970ae79bf9)
